# This command will take a photo every 5s for 10 minute...
raspistill -o /home/pi/time-lapse/image_%04d.jpg -tl 5000 -t 600000

# This command will construct a video file from the images...
avconv -r 10 -i /home/pi/time-lapse/image_%04d.jpg -r 10 -vcodec libx264 -crf 20 -g 15 timelapse.mp4
